variables:
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

image: maven:latest

cache:
  paths:
    - ".m2/repository/*"

stages:
  - build
  - documentation

test:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  rules:
    - when: always
  artifacts:
    paths:
      - "target/distribution/*.jar"
    reports:
      junit: "target/surefire-reports/*.xml"

pages:
  stage: documentation
  script:
    - mvn $MAVEN_CLI_OPTS package site
    - mv target/site public
  rules:
    - when: always
  artifacts:
    paths:
      - public