variables:
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

image: maven:latest

cache:
  paths:
    - .m2/repository

stages:
  - build
  - test
  - start_app

build-job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - "target/*.jar"
    reports:
      junit: "target/surefire-reports/*.xml"

test:
  stage: test
  script:
    - mvn test
    # When the test files are available
    #- mvn test -Dtest=ch.ladestation.connectncharge.controller.*,ch.ladestation.connectncharge.model.*

start_app:
  stage: start_app
  script:
    - mvn exec:java -Dexec.mainClass="ch.ladestation.connectncharge.AppStarter"
    - if [ "$?" -ne 0 ]; then echo "Failed to start AppStarter"; exit 1; fi

