# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven
env:
  MAVEN_CLI_OPTS: >-
    --file connectncharge/pom.xml
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn package $MAVEN_CLI_OPTS
    - name: Generate Project Pages
      run: mvn site $MAVEN_CLI_OPTS 
    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v1.0.8
      with:
        # Artifact name
        name: connectncharge-project-pages
        # Path of the directory containing the static assets.
        path: connectncharge/target/site
        # Duration after which artifact will expire in days.
        #retention-days: # optional, default is 1
    - name: Deploy GitHub Pages site
      uses: actions/deploy-pages@v2.0.1
      with:
        # GitHub token
        token: ${{ github.token }}
        # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
        #timeout: # optional, d#efault is 300000
        # Maximum number of status report errors before cancelling a deployment (default: 10)
        #error_count: # optional, default is 10
        # Time in milliseconds between two deployment status report (default: 5 seconds)
        #reporting_interval: # optional, default is 5000
        # Name of the artifact to deploy
        artifact_name: connectncharge-project-pages
        # Is this attempting to deploy a pull request as a GitHub Pages preview site? (NOTE: This feature is only in alpha currently and is not available to the public!)
        #preview: # optional, default is false
          
  # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
  #- name: Update dependency graph
  #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
